# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-01 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sujeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(help_text='Introduzca el c\xf3digo', max_length=3, unique=True, verbose_name='C\xf3digo')),
                ('nom', models.CharField(help_text='Introduzca el nombre', max_length=100, unique=True, verbose_name='Nombre')),
                ('formasocial', models.CharField(blank=True, help_text='Introduzca la forma social', max_length=10, null=True, verbose_name='Forma Social')),
            ],
            options={
                'verbose_name': 'Sujeto',
                'verbose_name_plural': 'Sujetos',
            },
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
